server:
  port: 81
  
spring:
  rabbitmq:
    host: 192.168.199.130
    port: 5672
    username: admin
    password: admin
    # 默认就是 /
    virtual-host: /
    # 开启ACK(确认回执) 手动确认收到消息
    listener:      simple:        acknowledge-mode: manual  # 默认none 收到消息立即返回接收成功  manual需要手动调用返回回执