server:
  port: 80
 
spring:  rabbitmq:    host: 192.168.199.130
    port: 5672
    username: admin
    password: admin
    # 默认就是 /
    virtual-host: /
    # 开启confirm确认模式
    publisher-confirm-type: correlated
    # 开启回退模式
    publisher-returns: true
    
    